# Parameters for docker build
version: '3'
services:
  simulator:

    build: # the OS, PL, and Libs required are specified in the Dockerfile
      context: .
      dockerfile: Dockerfile

    volumes: # Mount both the repo and the data
      - '.:/ReEMS/Algorithms'



  # volumes:
  #   - '.'
